### ISSUE TITLE
Remove `Edit`/`Save` button

### ISSUE THREAD

**Issue by ivanjolic95** [ivanjolic95/vue-layout-composer#4]
State toggling button (`Edit`/`Save`) should be removed, and developers should handle changing state themselves.

![Screenshot from 2020-01-24 15-32-55](https://user-images.githubusercontent.com/6699258/73076680-df57c100-3ebe-11ea-9642-f81e22ad9265.png)

**Comment by matijamatija** [comment]
This sucks

**Comment by matijamatija** [comment]
Dlt pls
